export default (defaultStyles = {
  primaryColor: '#55AADE',
  secondaryColor: '#A0C5CE',
  bgPrimaryColor: '#FFFFFF',
  bgSecondaryColor: '#F5F5F5',
  txtPrimaryColor: '#292828',
  txtSecondaryColor: '#FFFFFF',
  txtTeritaryColor: '#C4C4C4',
  buttonColor: '#38B381',
  icBar: '#FFFFFF',
  txtWhite: '#FFFFFF',
  lineColor: '#C4C4C4',
  yellow: '#FAD410',
  green: '#38B381',
  blue: '#2E75A7',
  fontRegular: 'Montserrat-Regular',
  fontMedium: 'Montserrat-Medium',
  fontSemiBold: 'Montserrat-SemiBold',
  fontBold: 'Montserrat-Bold'
});
